pipeline {
    agent any

    environment {
        GITHUB_CREDS_ID = 'github-credentials'
        DOCKER_HUB_CREDS_ID = 'dockerhub-credentials'
        DOCKER_IMAGE = 'dorfin/messaging_app' 
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    credentialsId: "${GITHUB_CREDS_ID}", 
                    url: 'https://github.com/dorphines/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                pip install pytest pytest-django
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                mkdir -p reports
                export DJANGO_SETTINGS_MODULE=messaging_app.settings
                python3 -m pytest messaging_app/ \
                    -o "python_files=test_*.py *_test.py tests.py" \
                    --junitxml=reports/test-results.xml
                '''
            }
        }

        stage('Build Docker Image') {
            environment {
                DOCKER_BUILDKIT = '0'
            }
            steps {
                // Force legacy builder to avoid potential registry 400 errors with buildx/provenance
                sh "docker build --no-cache --pull -t ${DOCKER_IMAGE}:${env.BUILD_ID} ./messaging_app"
                sh "docker tag ${DOCKER_IMAGE}:${env.BUILD_ID} ${DOCKER_IMAGE}:latest"
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_CREDS_ID}", passwordVariable: 'DOCKER_HUB_PASSWORD', usernameVariable: 'DOCKER_HUB_USER')]) {
                    // We logout first to clear any stale sessions on the socket
                    sh "docker logout"
                    sh "echo \$DOCKER_HUB_PASSWORD | docker login -u \$DOCKER_HUB_USER --password-stdin"
                    sh "docker push ${DOCKER_IMAGE}:${env.BUILD_ID}"
                    sh "docker push ${DOCKER_IMAGE}:latest"
                }
            }
        }
    }

    post {
        always {
            junit 'reports/test-results.xml'
        }
        cleanup {
            // Clean up the images so they don't clog your computer
            sh "docker rmi ${DOCKER_IMAGE}:${env.BUILD_ID} ${DOCKER_IMAGE}:latest || true"
        }
    }
}